apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-eks-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-eks-app
  template:
    metadata:
      labels:
        app: my-eks-app
    spec:
      containers:
        - name: my-eks-app
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 80
